services:
  - type: web
    name: chatbot-fracciones
    env: python
    plan: free
    buildCommand: "chmod +x setup.sh && ./setup.sh"
    startCommand: "source venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
